# Generated by Django 5.1.7 on 2025-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_listings',
            field=models.IntegerField(default=0),
        ),
    ]
